### ISSUE TITLE
What is the process of creating a custom dataset and train with this implementation

### ISSUE THREAD

**Issue by pksorensen** [wkentaro/chainer-mask-rcnn#11]
Hello, this project looks very nice.

Would it be possible to outline what the steps are to create my own dataset for training. 
I have two datasets that I would like try try with.

1) A folder of natrual images and polygons with labels for objects to segment. Maybe it can benefit for pretrained models as images are RGB.
2) A folder of sat images where there are 10 bands and also polygons with labels.

I can easily transform the polygons into mask files if needed. (what is most used label format?)
I assume that for sat images, there exists no pretrained models, so have to do it all from the bottom.

Would be super cool if a few steps/guidelines for what I should study to train on top of my own data.

**Comment by wkentaro** [comment]
You need create a python dataset class as the VOC example here.
https://github.com/wkentaro/chainer-mask-rcnn/blob/838defb53f1fd96d55a2ac353c792230f2cb29c5/chainer_mask_rcnn/datasets/voc/sbd.py#L16-L70
Specifically, the returning variables of `def get_example(self, index):` are important.

After you create the dataset class, you can use it in the train.py:
https://github.com/wkentaro/chainer-mask-rcnn/blob/838defb53f1fd96d55a2ac353c792230f2cb29c5/examples/voc/train.py#L79-L80

---

I will add an example of training a model with a custom dataset, but you can follow above instructions to start training for your project.

**Comment by pksorensen** [comment]
Thanks, i will give it a go and see if I can figure it out. Whats your take on multi band images. If i have sample images with 10+ bands, should i just follow these steps also? Dont I somehow also need to alter the network as there are now many more variables?

**Comment by wkentaro** [comment]
I created an example of using a custom dataset in https://github.com/wkentaro/chainer-mask-rcnn/pull/21.
I hope that would be helpful.

**Comment by pksorensen** [comment]
Cool, i will take a look as soon as a bit of time frees up. Thank you

**Comment by pksorensen** [comment]
I finally got to try it out, but ran into problems due to not having a cuda device on my laptop :)

Are there any way to make the common train work with arguments to train on CPU. Just experimenting with the simple custom dataset and i am guessing that a CPU should do for this?
