### ISSUE TITLE
Printing the file name in evaluator.py / evaluate_common.py 

### ISSUE THREAD

**Issue by deeponcology** [wkentaro/chainer-mask-rcnn#27]
Hi, 
Is it possible to print the image name to a log file during inference? or even better, print the image name on the image itself? 
Thanks,

**Comment by wkentaro** [comment]
You mean write filenames on the `latest.jpg`?

**Comment by bayesianio** [comment]
Yes, instead of 'iteration=best'+str(ii)+'.jpg' I want real_file_name

**Comment by wkentaro** [comment]
Maybe you can change `demo.py` for that.
