### ISSUE TITLE
The accuracy in result

### ISSUE THREAD

**Issue by weiqiyang** [wkentaro/chainer-mask-rcnn#30]
I tried your training example with my own custom dataset.
In my case, accuracy.png in `logs\` shows that the accuracy holds steady at 48% after 7000 iterations.
I wonder whether it is good enough, and whether need I prepare a larger dataset.
Could you provide a standard to judge the result, i.e. above how much is considered good, and under how much is bad?

Also, I noticed that you iterated the same dataset 20 times in your train.py. 

> https://github.com/wkentaro/chainer-mask-rcnn/blob/c8e235000d425d710eed0f3e0e11e0ee8b836d03/examples/custom_dataset/train.py#L72

I tried my training with and without this line (after modified to fit my dataset), and the results are totally different.
Is there a specific reason that you choose the number 20? Or is it just simply the larger the better (without considering training time)?

**Comment by wkentaro** [comment]
The reason why I multiply 20 is to mimic a certain size dataset from 3 images.
Because the example only has 3 images which are annotated and the epoch finishes soon after 3 iterations.

You may refer to the paper to know about the accuracy or README of this repo.
